//开拍会员
//Auth：Andy
//2026年06月22日 16:56:56

^https?:\/\/api\.account\.meitu\.com\/users\/show_current\.json|https?:\/\/api-sub\.meitu\.com\/v2\/user\/info_by_entrance\.json|https?:\/\/api-sub\.meitu\.com\/v2\/user\/vip_info\.json|https?:\/\/api\.dreamavatar\.com\/v1\/api\/2d\/product\/query|https?:\/\/api\.dreamavatar\.com\/v1\/api\/2d\/ai\/video\/pretreate|https?:\/\/api\.dreamavatar\.com\/v1\/api\/2d\/user\/rights|https?:\/\/api\.dreamavatar\.com\/v1\/api\/2d\/ai\/video\/generate.*? url script-response-body https://raw.githubusercontent.com/andyeason/quanX/main/Scripts/kaipai.js
hostname = api.account.meitu.com,api-sub.meitu.com,api-sub.meitu.com,api.dreamavatar.com,api.dreamavatar.com,api.dreamavatar.com,api.dreamavatar.com


