# [rewrite_local] 规则区域
^https?:\/\/(h5\.xiuxiu\.meitu\.com\/v1\/h5\/vip\/new_sub_detail\.json|api\.xiuxiu\.meitu\.com\/v1\/vip\/vip_show\.json|api-sub\.meitu\.com\/(v1\/vip\/(prompt\/query\.json|sub_popup\.json)|v2\/user\/(vip_info\.json|info_by_entrance\.json))) url script-response-body https://raw.githubusercontent.com/andyeason/quanX/main/Scripts/kaipai.js

# [mitm] 区域 (必须包含美图相关域名)
[mitm]
hostname = h5.xiuxiu.meitu.com, api.xiuxiu.meitu.com, api-sub.meitu.com