//开拍会员
//Auth：Andy
//2026年06月22日 16:56:56
//配置地址：https://raw.githubusercontent.com/andyeason/quanX/main/Rewrites/xiaowai.conf
//脚本地址：https://raw.githubusercontent.com/andyeason/quanX/main/Scripts/xiaowai.js

^https?:\/\/api-sub\.meitu\.com\/v2\/user\/(login_vip_check|vip_info|info_by_entrance).*json url script-response-body https://raw.githubusercontent.com/andyeason/quanX/main/Scripts/kaipai.js
hostname = api-sub.meitu.com


